### ISSUE TITLE
Add more frequently used snippet of codes

### ISSUE THREAD

**Issue by oktak** [oktak/Snippet#1]
## Python

- virtual environment

- unit test

- timeit

- import modules

- requests

- beautifulsoup

- pandas, json, csv

- argparse

- datetime

- asynic, aiohttp

- Flask

- redis queue

**Comment by kennedy69** [comment]
bruhh....

**Comment by edoardottt** [comment]
A bit too general...ahah Can you be more precise in what you're searching for?
